IF
	Global("VP_Sime_Aran","GLOBAL",1)
	NumTimesTalkedTo(0)
	See("vpsime")
THEN
	RESPONSE #100
		Dialogue("vpsime")
END

IF
	Global("VP_Sime_Aran","GLOBAL",1)
	NumTimesTalkedTo(0)
	!See("vpsime")
THEN
	RESPONSE #100
		MoveToObject("vpsime")
		StartDialogueNoSet("vpsime")
END

IF
	Global("VP_AranLeaves","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("VP_AranLeaves","GLOBAL",2)
		ReallyForceSpell(Myself,DRYAD_TELEPORT)
END
